server:
  port: 80
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apms?serverTimezone=Asia/Shanghai
    username: root
    password: password
  redis: # redis??
    host: 127.0.0.1 # IP
    port: 6379  # ??
    password:  # ??
    connect-timeout: 10s  # ??????
    lettuce: # lettuce redis?????
      pool: # ?????
        max-active: 8  # ???????????????????? ?? 8
        max-wait: 200s  # ??????????????????????? ?? -1
        max-idle: 8 # ??????????? ?? 8
        min-idle: 0 # ??????????? ?? 0


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml